apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      resources:
        requests:
          cpu: 250m
          memory: "64M"
        limits:
          cpu: 500m
          memory: "128M"


# resource quota can be granular and put up limit on specific resource types like requests and limits separately.
