apiVersion: v1
kind: PersistentVolume
metadata:
 name: demo-pv
spec:
 storageClassName: manual # Logical storage class name used to match with PVC (must match on both sides)
 capacity: 
  storage: 2Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: /mnt/data # On the resource storage (wherever be it) the path where the persisted data goes 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: demo-pvc
spec: 
 storageClassName: manual # This should match the storage class name of the PV
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 2Gi 

--- 
apiVersion: v1
kind: Pod
metadata: 
 name: nginx-with-pvc
spec:
 containers:
 - name: nginx
   image: nginx 
   ports: 
   - name: http
     containerPort: 80
     protocol: TCP
   volumeMounts:  # This is where we mount the volume to the container   
   - name: nginx-pv-storage
     mountPath: /data
 volumes:  # Defines storage available to this Pod (can be mounted by its containers)
 - name: nginx-pv-storage
   persistentVolumeClaim:
    claimName: demo-pvc # This should match the name of the PVC we created above